//firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp3SLtt_VZ0L70yjGnCNWkJ4H_d9dRElI',
    appId: '1:11760939212:web:987a4465d55340ed761269',
    messagingSenderId: '11760939212',
    projectId: 'tododenemesi',
    authDomain: 'tododenemesi.firebaseapp.com',
    storageBucket: 'tododenemesi.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyColWorOTKG9bocKHYllhjyy_ynvyc3vgo',
    appId: '1:11760939212:android:741e1049d45f3618761269',
    messagingSenderId: '11760939212',
    projectId: 'tododenemesi',
    storageBucket: 'tododenemesi.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp3SLtt_VZ0L70yjGnCNWkJ4H_d9dRElI',
    appId: '1:11760939212:web:d595fdd3e119bd5a761269',
    messagingSenderId: '11760939212',
    projectId: 'tododenemesi',
    authDomain: 'tododenemesi.firebaseapp.com',
    storageBucket: 'tododenemesi.firebasestorage.app',
  );

}